name: GitHub Notifier for Teams
description: "Send gihub issues and pull requests notifications via Teams channel"
author: "Pablo Velasco"

branding:
  icon: "bell"
  color: "purple"

inputs:
  teamsSecret:
    description: 'Teams secret'
    required: true
  
runs: 
  using: "composite"

  steps:

      - name: Config Node.js & npm
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        shell: bash
        run: npm install axios

      - name: Send teams message
        shell: bash
        env:
          CONTEXT: "${{toJson(github.event)}}"
          TEAMS: ${{ inputs.teamsSecret }}
        run: node script.js