name: GitHub Notifier for Teams
description: "Send gihub issues and pull requests notifications via Teams channel"
author: "Pablo Velasco"

branding:
  icon: "bell"
  color: "purple"

inputs:
  teamsSecret:
    description: 'Teams secret'
    required: true
  
runs: 
  using: "composite"

  steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Retrieve File
        shell: bash
        run: |
          # Clonar el repositorio
          git clone https://github.com/pablovelascoedisa/github-notifications-teams-action /tmp/repo/teams

      - name: Config Node.js & npm
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Send teams message
        shell: bash
        env:
          CONTEXT: "${{toJson(github.event)}}"
          TEAMS: ${{ inputs.teamsSecret }}
        run: |
          cd /tmp/repo/teams
          npm install axios
          node script.js